# .github/workflows/deploy-gh-pages.yml
name: Deploy GitHub Pages

on:
  workflow_call:
    inputs:
      GH_PAGES_BRANCH:
        required: false
        type: string
        default: "gh-pages"
      GH_PAGES_DIR:
        required: false
        type: string
        default: "/tmp/gh-pages"
      DOCS_PATH:
        required: false
        type: string
        default: "docs"
      CREATE_PAGES_ON_FAILURE:
        required: false
        type: boolean
        default: false
    secrets:
      DEPLOY_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ inputs.CREATE_PAGES_ON_FAILURE || success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ssh auth
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          sudo apt-get update -y
          which ssh-agent || ( sudo apt-get update -y && sudo apt-get install openssh-client -y )
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          sudo ssh-keyscan github.com >> ~/.ssh/known_hosts
          sudo ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          echo "${DEPLOY_TOKEN}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "${DEPLOY_TOKEN}"
          cat ~/.ssh/id_rsa
#          git config --global user.email "${GITLAB_USER_NAME}"
#          git config --global user.name "${GITLAB_USER_EMAIL}"


      - name: Configure Git
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Setup gh-pages branch
        id: setup
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          GH_PAGES_BRANCH="${{ inputs.GH_PAGES_BRANCH}}"
          GH_PAGES_DIR="${{ inputs.GH_PAGES_DIR}}"
          
          echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:+yes}"

          REPO_URL="git@github.com:${{ github.repository }}.git"
          if git ls-remote --exit-code --heads $REPO_URL $GH_PAGES_BRANCH; then
            git clone --branch $GH_PAGES_BRANCH $REPO_URL $GH_PAGES_DIR
            cd $GH_PAGES_DIR/docs || mkdir -p $GH_PAGES_DIR/docs
            git rm -r "${GITHUB_REF_NAME}" || true
          else
            mkdir -p $GH_PAGES_DIR/docs
            cd $GH_PAGES_DIR
            git init
            git remote add origin $REPO_URL
            sudo git fetch origin
            git checkout -b $GH_PAGES_BRANCH
            cd docs
            echo "<meta http-equiv=\"refresh\" content=\"0; url=https://${{ github.repository_owner }}.github.io/${{ github.repository }}/main/docs/index.html\">" > index.html
            touch .nojekyll
          fi

      - name: Copy docs folder
        run: |
          GH_PAGES_DIR="${{ inputs.GH_PAGES_DIR}}"
          cp -r ${{ inputs.DOCS_PATH }} "${GH_PAGES_DIR}/${GITHUB_REF_NAME}/"

      - name: Delete folders older than 14 days
        run: |
          GH_PAGES_DIR=${{ steps.setup.outputs.GH_PAGES_DIR }}
          cd $GH_PAGES_DIR/docs

          remote_branches=$(git for-each-ref --format='%(refname:lstrip=3)' refs/remotes/origin)

          for folder in */; do
            folder=${folder%/}
            if [[ "$folder" == "development" || "$folder" == "main" || "$folder" == "master" ]]; then
              echo "Skipping folder $folder (protected branch)"
              continue
            fi
            if echo "$remote_branches" | grep -q "^$folder$"; then
              last_commit_date=$(git log -1 --format="%ci" "origin/$folder")
              last_commit_ts=$(date -d "$last_commit_date" +%s)
              current_ts=$(date +%s)
              days_diff=$(( (current_ts - last_commit_ts) / 86400 ))
              if (( days_diff >= 180 )); then
                echo "Deleting folder $folder (no commits in $days_diff days)"
                rm -rf "$folder"
              else
                echo "Keeping folder $folder (commits within $days_diff days)"
              fi
            else
              echo "Folder $folder not associated with remote branch, skipping deletion"
            fi
          done

      - name: Commit and push changes
        run: |
          GH_PAGES_DIR="${{ inputs.GH_PAGES_DIR}}"
          cd $GH_PAGES_DIR
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update docs for $GITHUB_REF_NAME and cleanup old branches"
            git push origin gh-pages
          fi
