name: Semantic Release

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: false
        type: string
        default: "3.10"
      DIRECTORY:
        required: false
        type: string
        default: "."
      COMMIT_SUBJECT:
        required: false
        type: string
        default: "chore(release): version {version}"
    secrets:
      TOKEN:
        required: true
#        type: string

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git config
        run: |
          git config user.email "semantic-release@github-actions"
          git config user.name "semantic-release (via GitHub Actions)"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Set Git remote to use token
        run: git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}.git
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}

      - name: Install semantic-release
        run: pip install python-semantic-release --disable-pip-version-check

      - name: Change directory
        if: ${{ inputs.DIRECTORY != '.' }}
        run: cd ${{ inputs.DIRECTORY }}

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          COMMIT_SUBJECT: ${{ inputs.COMMIT_SUBJECT }}
        run: |
          echo "Running semantic-release in: ${{ inputs.DIRECTORY }}"
          cd ${{ inputs.DIRECTORY }}
          semantic-release version
